[project]
name = "task1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "educhain>=0.3.10",
    "google-genai>=1.24.0",
    "mcp>=1.10.1",
]
